[
   // A unique identifier that distinguishes this
   // interface from other interfaces.
   uuid(054c8475-3e9f-45fc-bd55-723218e0503c),

   // This is version 1.0 of this interface.
   version(1.0),

   // This interface will use an implicit binding
   // handle named hExample1Binding.
   implicit_handle(handle_t hApexBinding)
]
interface apex 
{
	void clearVariable(
		[in, string] const char* name );
	void clearAll( );
	void saveWorkspace(
		[in, string] const char* workspaceName );
   // store or retreive an array of doubles.
   void storeDoubleArray(
      [in, string] const char* name,
	  [in] unsigned long arraySize,
      [in] [size_is(arraySize)] const double array[*] );
   void checkLengthDoubleArray(
      [in, string] const char* name,
	  [out] unsigned long *arraySize);
   void retreiveDoubleArray(
      [in, string] const char* name,
	  [in] unsigned long arraySize,
      [out] [size_is(arraySize)] double array[*] );
}